Feature/about/mobile
vladkrasovsky/icecream pull request #24
Opened 2022-07-15 20:26 UTC by Vi7ality

2022-07-15 21:22 UTC, vladkrasovsky requested changes

2022-07-15 21:22 UTC, vladkrasovsky commented on src/sass/layout/_about.scss
> +  @media screen and (min-device-pixel-ratio: 2),
Є готовий міксин для підтримки 2х

2022-07-15 21:22 UTC, vladkrasovsky commented on src/partials/about.html
> +    <h2 class="about__title title">how it's made?</h2>
Потрібно центрувати

2022-07-16 09:43 UTC, Vi7ality commented on src/sass/layout/_about.scss
> +  @media screen and (min-device-pixel-ratio: 2),
Done

2022-07-16 09:43 UTC, Vi7ality commented on src/partials/about.html
> +    <h2 class="about__title title">how it's made?</h2>
Done

2022-07-16 11:16 UTC, vladkrasovsky approved these changes

2022-07-16 11:16 UTC, merged