header html layout added
vladkrasovsky/icecream pull request #5
Opened 2022-07-14 08:14 UTC by vokur13

Page header html layout added

2022-07-14 20:09 UTC, vladkrasovsky requested changes

2022-07-14 20:09 UTC, vladkrasovsky commented on src/partials/header.html
> +    <a href="#" class="logo">
Посилання логотипу має вести на головну сторінку

2022-07-14 20:09 UTC, vladkrasovsky commented on src/partials/header.html
> +        <!-- <use class="logo__icon" href=""></use> -->
Можна додавати svg іконки вже є в проекті. Оновіть у себе гілку main та додайте зміни до вашої гілки.

2022-07-14 20:09 UTC, vladkrasovsky commented on src/partials/header.html
> +          <!-- <use class="nav__icon nav__icon--close" href="#"></use> -->
Тут також, вже маємо svg, можна додавати.

2022-07-14 20:09 UTC, vladkrasovsky commented on src/partials/header.html
> +    <button type="button" class="button header__mdl">Buy now</button>
В компонентах вже класи, які можна використати для оформлення кнопки .btn

2022-07-15 10:36 UTC, vokur13 commented on src/partials/header.html
> +    <a href="#" class="logo">
Done

2022-07-15 10:36 UTC, vokur13 commented on src/partials/header.html
> +        <!-- <use class="logo__icon" href=""></use> -->
Done

2022-07-15 10:37 UTC, vokur13 commented on src/partials/header.html
> +    <button type="button" class="button header__mdl">Buy now</button>
Done as draft, to be fixed upon styling

2022-07-15 22:05 UTC, vladkrasovsky approved these changes

2022-07-15 22:05 UTC, merged