advantages html
vladkrasovsky/icecream pull request #9
Opened 2022-07-14 13:44 UTC by IreneCreadora

2022-07-14 20:38 UTC, vladkrasovsky requested changes

2022-07-14 20:38 UTC, vladkrasovsky commented on src/partials/advantages.html
> +        <div class="advantages__wrapper">
Для чого потрібен div wrapper?

2022-07-14 20:38 UTC, vladkrasovsky commented on src/partials/advantages.html
> +                    <h3 class="advantages__title">721</h3>
Для семантики HTML, краще прибрати тут теги заголовків. Ось ці цифри, є більш декоративними.

2022-07-15 04:43 UTC, IreneCreadora commented on src/partials/advantages.html
> +                    <h3 class="advantages__title">721</h3>
змінити на <p> ?

2022-07-15 04:45 UTC, IreneCreadora commented on src/partials/advantages.html
> +        <div class="advantages__wrapper">
я не впевнена що він точно необхідний, в меге погано з уявою того як проставляти  флекси, можу проставити вже тільки під час написання стилів. Тому я "перестрахувалася". Необхідно прибрати?

2022-07-15 04:46 UTC, IreneCreadora commented on src/partials/advantages.html
> +                    <h3 class="advantages__title">721</h3>
там в коменті чомусь не відобразився тег р . на нього змінити?

2022-07-15 05:08 UTC, vladkrasovsky commented on src/partials/advantages.html
> +        <div class="advantages__wrapper">
Відштовхуюємось від мінімуму, тобто, спочатку пишеш явні по макету елементи. Якщо в процесі стилізації, будь ніяк без дод. обгортки, тоді й додаси. Краще уникати зайвого коду.

2022-07-15 05:09 UTC, vladkrasovsky commented on src/partials/advantages.html
> +                    <h3 class="advantages__title">721</h3>
Так

2022-07-15 06:11 UTC, vladkrasovsky commented
Створила новий PR, тому цей закриваю.

2022-07-15 06:11 UTC, closed without merging